[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "comparis-airflow-plugins"
version = "0.1.0"
requires-python = "~=3.11"
dependencies = [
    "apache-airflow==2.7.3",
]
